### ISSUE TITLE
character limits

### ISSUE THREAD

**Issue by leonardas103** [RUGSoftEng/2017-Medical-ID#15]
For the card a label should have maxlength of 11and valuefield 19.
[Optional:] there should be a flash message saying "only a maximum of 10 fields can be shown on a card".

For a document the valuefield should be maxlength of 57.

**how to fix:** 
set max values for the document in creator.js, then in card.js loop over fields and labels and truncate their values.

**Comment by leonardas103** [comment]
added new limits, did not add flash message

**Comment by Theys96** [comment]
Are you sure about these limits? How did you come up with them?
I will add a flash message.

**Comment by Theys96** [comment]
I think it may be better make it a possibility to define the label/field lengths in the document-specific creators.

**Comment by Theys96** [comment]
Did the above ^
It's pretty fine now.
