### ISSUE TITLE
Issue with Sharp package

### ISSUE THREAD

**Issue by Matt1994** [RUGSoftEng/2017-Medical-ID#24]
Trying to start the node file, I now get errors about Sharp. Seems to be because it needs node-gyp to install, which in turn requires python 2.7.0-3.0.0 installed

**Comment by leonardas103** [comment]
sharp is used on the image. Adding it to the package.json ensures that npm install installs all of its dependencies. There's no problem running it on Heroku.

**Comment by leonardas103** [comment]
Are you sure this is related to sharp?

**Comment by leonardas103** [comment]
http://localhost:3000/js/pdfmake.js  and
http://localhost:3000/js/vfs_fonts.js
creating these file paths fixes the problem on my end.

**Comment by Matt1994** [comment]
That is unrelated to this problem

**Comment by Matt1994** [comment]
Issue was on my end locally
