### ISSUE TITLE
Code field is missing?

### ISSUE THREAD

**Issue by mavagio** [RUGSoftEng/2017-Medical-ID#35]
When making a card, I did not get Code/ID field on the card, only a qr code was there. Is this expected ? if so why do you have the code field in the website, if not, is this a bug ?
For card
![image](https://cloud.githubusercontent.com/assets/7386708/25711527/6c039434-30ef-11e7-8558-16dc0b231962.png)
For document
![image](https://cloud.githubusercontent.com/assets/7386708/25711824/2882ce4a-30f0-11e7-85f7-79adf1a49f36.png)

**Comment by Theys96** [comment]
Hello,
This is not so much a bug as a implemented feature. The code entry on the website is for people without a scanner, but then of course we still need to print the code on the card!
Thanks for the reminder, I had actually forgotten we still needed to do this.

**Comment by Matt1994** [comment]
This is more because the code is still being implemented at the moment. The code field on the website used to take the id of the user in the database and use that to find the requested user, however we're in the middle of converting this to a different, 12 character code.

**Comment by Matt1994** [comment]
The latest merge to Develop has now implemented the new code
