### ISSUE TITLE
Document creator does not work.

### ISSUE THREAD

**Issue by mavagio** [RUGSoftEng/2017-Medical-ID#4]
Using the [view](https://htmlpreview.github.io/?https://raw.githubusercontent.com/RUGSoftEng/2017-Medical-ID/develop/index.html) provided in the readme the document creator does not work.

![image](https://cloud.githubusercontent.com/assets/7386708/23879505/f3fd5ab6-084d-11e7-8464-feb2792f075a.png)

**Comment by Theys96** [comment]
This was a known issue which we hope to fix in the future, but it only happens in the htmlpreview.

**Comment by mavagio** [comment]
Alright just letting you know.

**Comment by Theys96** [comment]
Yes thanks anyway :)
