### ISSUE TITLE
Logging in should not tell you whether the password is wrong or the user doesn't exists

### ISSUE THREAD

**Issue by Theys96** [RUGSoftEng/2017-Medical-ID#54]
Instead, it should just be one 'login failed' message.

**Comment by leonardas103** [comment]
Sites like google tell you whether the email is invalid or if it's the password.

**Comment by Matt1994** [comment]
Which is bad, since this can be used to crack accounts much more easily. If it tells you invalid password, then you know that the email address definitely exists in the system.

**Comment by Theys96** [comment]
Fixed in 'adjust' branch.
