### ISSUE TITLE
Forgot password throwing error

### ISSUE THREAD

**Issue by Matt1994** [RUGSoftEng/2017-Medical-ID#55]
After entering the email and clicking submit, Internal Server Error appears. Bizarrely, running locally there are no issue. Considering the code on Heroku and the develop branch here are identical, it doesn't make a lot of sense

**Comment by leonardas103** [comment]
1. Sometimes for user lookup(findOne) and user.email returns test@test.com instead of actual email address.
2. Might not be related but there are some dependencies outdated that show up in the console log.

Yesterday the forgot password on heroku was working fine.

**Comment by ecoostwal** [comment]
Error has been resolved
