### ISSUE TITLE
Tether warning

### ISSUE THREAD

**Issue by leonardas103** [RUGSoftEng/2017-Medical-ID#76]
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

**Comment by Matt1994** [comment]
When does this occur?

**Comment by leonardas103** [comment]
In /create. Seems to be only firefox related.

**Comment by Matt1994** [comment]
I can't replicate this at all, both as guest and logged in

**Comment by Matt1994** [comment]
Testing (and a quick google search) indicates this is an issue on firefox version 47 and below. Mine is the most up to date and I have no issue. When on 47, I see the error, and on 48 it disappears
