### ISSUE TITLE
Verification e-mail

### ISSUE THREAD

**Issue by Theys96** [RUGSoftEng/2017-Medical-ID#79]
Can we call the verification e-mail "Medical ID registering: e-mail verification" or something instead of "Node.js Verify email" which would make no sense to an actual user.
Furthermore, HTML in the mail doesn't seem to work for me (is the appropriate header set?).

**Comment by Matt1994** [comment]
Nodemailer has two options: text and html. Text is what is used if someones mail client can't render the html. We currently send with the body in the text option. We need to move this to the html option and put some non-html stuff in the text part.

**Comment by Matt1994** [comment]
I'm actually going to start using HTML templates for this.

**Comment by Matt1994** [comment]
I have resolved this on pull request #89
