### ISSUE TITLE
Chrome issues

### ISSUE THREAD

**Issue by Matt1994** [RUGSoftEng/2017-Medical-ID#8]
The document creators are extremely buggy in Chrome. Works fine in all other browsers.

**Comment by leonardas103** [comment]
I notice a half second lag when the data loads into the field. And when logged in, the document creator PDF preview does not load and the download and back buttons don't work.

**Comment by Matt1994** [comment]
The preview stuff and the buttons appear to be related to RequireJS, I get some errors in all browsers regarding stuff from it. Interestingly, if you go the card creator page and click create, then go back to the document page, the back and download button work fine, like there is something that isn't being loaded properly on the document page that is being loaded when you go to the card page

**Comment by Matt1994** [comment]
Leo did you try it in Firefox as well?

**Comment by Theys96** [comment]
Please re-issue the specific problems so we can close this one.

**Comment by Matt1994** [comment]
Will do
